---

- name: "Check OS family"
  fail: msg="This only works on Linux"
  when: ansible_system != 'Linux'

- name: "Run for each target OS"
  include: os.yml
  with_items: "{{ bobnet_oses.values()|unique }}"
  loop_control:
    loop_var: bobnet_os
