bobnet_os: "hypriot"

bobnet_wifi_ssid: "dummy"
bobnet_wifi_passphrase: "dummy"

bobnet_ansible_user_password: "dummy"
bobnet_ansible_user_public_key: "dummy"

bobnet_hosts:
  - bob01
  - bob02
  - bob03

bobnet_networking:
  bob01:
    eth0_ipv4_address: "192.0.2.65"
  bob02:
    eth0_ipv4_address: "129.0.2.66"
  bob03:
    eth0_ipv4_address: "129.0.2.67"
